language = "de"
theme = "latte" # Options: latte, frappe, macchiato, mocha
accent = "green" # Options: rosewater, flamingo, pink, mauve, red, maroon, peach, yellow, green, teal, blue, sky, sapphire, lavender
text-font = "Arial"
header-font = "Bahnschrift"

[author]
    firstname = "Max"
    lastname = "Mustermann"
    email = "test@test.de"
    profile-picture = "profile.png" # False if not wanted
    homepage = "homepage"

    website = "test"
    linkedin = "LinkedInUsername"
    bitbucket = "BitbucketUsername"
    twitter = "TwitterUsername"
    google-scholar = "GoogleScholarUsername"
    orcid = "0000-0000-0000-0000"

    phone = "+49 123 4567890"
    github = "GithubUsername"
    gitlab = "GitlabUsername"
    birth = "1990-01-01"
    address = "Musterstraße 1, 12345 Musterstadt"
    positions = [
      "Software Engineer",
      "Software Architect", 
      "Developer",
    ]
